class MSSM:
    def __init__(self, param: dict[str, float]) -> None: ...
    def cllHH(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cG(self, mubarsq: float, hbar: float) -> float: ...
    def cW(self, mubarsq: float, hbar: float) -> float: ...
    def cGt(self, mubarsq: float, hbar: float) -> float: ...
    def cWt(self, mubarsq: float, hbar: float) -> float: ...
    def cH(self, mubarsq: float, hbar: float) -> float: ...
    def cHBox(self, mubarsq: float, hbar: float) -> float: ...
    def cHD(self, mubarsq: float, hbar: float) -> float: ...
    def cHG(self, mubarsq: float, hbar: float) -> float: ...
    def cHW(self, mubarsq: float, hbar: float) -> float: ...
    def cHB(self, mubarsq: float, hbar: float) -> float: ...
    def cHWB(self, mubarsq: float, hbar: float) -> float: ...
    def cHGt(self, mubarsq: float, hbar: float) -> float: ...
    def cHWt(self, mubarsq: float, hbar: float) -> float: ...
    def cHBt(self, mubarsq: float, hbar: float) -> float: ...
    def cHWtB(self, mubarsq: float, hbar: float) -> float: ...
    def ceH(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cuH(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cdH(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def ceW(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def ceB(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cuG(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cuW(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cuB(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cdG(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cdW(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cdB(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHl1(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHl3(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHe(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHq1(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHq3(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHu(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHd(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cHud(self, i1: int, i2: int, mubarsq: float, hbar: float) -> float: ...
    def cll(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqq1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqq3(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def clq1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def clq3(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cee(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cuu(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cdd(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def ceu(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def ced(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cud1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cud8(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cle(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def clu(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cld(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqe(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqu1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqu8(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqd1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqd8(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cledq(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cquqd1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cquqd8(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def clequ1(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def clequ3(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cduq(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqqu(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cqqq(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
    def cduu(self, i1: int, i2: int, i3: int, i4: int, mubarsq: float, hbar: float) -> float: ...
