class Task: ...

class MSSM:
    def __init__(self, param_dict: dict[str, complex], scale: float, loop: bool) -> None: ...
    def updateParams(self, param_dict: dict[str, complex]) -> None: ...
    def getScale(self) -> float: ...
    def setScale(self, scale: float) -> None: ...
    def loopContributions(self, loop: bool) -> None: ...
    def getParams(self) -> dict[str, complex]: ...
    def batch_eval(self, tasks: list[Task]) -> dict[str, complex]: ...
    def wrap_0f(self, name: str, method_name: str) -> Task: ...
    def wrap_2f(self, name: str, method_name: str, i1: int, i2: int) -> Task: ...
    def wrap_4f(self, name: str, method_name: str, i1: int, i2: int, i3: int, i4: int) -> Task: ...
    def cllHH(self, i1: int, i2: int) -> complex: ...
    def cG(self) -> complex: ...
    def cW(self) -> complex: ...
    def cGt(self) -> complex: ...
    def cWt(self) -> complex: ...
    def cH(self) -> complex: ...
    def cHBox(self) -> complex: ...
    def cHD(self) -> complex: ...
    def cHG(self) -> complex: ...
    def cHW(self) -> complex: ...
    def cHB(self) -> complex: ...
    def cHWB(self) -> complex: ...
    def cHGt(self) -> complex: ...
    def cHWt(self) -> complex: ...
    def cHBt(self) -> complex: ...
    def cHWtB(self) -> complex: ...
    def ceH(self, i1: int, i2: int) -> complex: ...
    def cuH(self, i1: int, i2: int) -> complex: ...
    def cdH(self, i1: int, i2: int) -> complex: ...
    def ceW(self, i1: int, i2: int) -> complex: ...
    def ceB(self, i1: int, i2: int) -> complex: ...
    def cuG(self, i1: int, i2: int) -> complex: ...
    def cuW(self, i1: int, i2: int) -> complex: ...
    def cuB(self, i1: int, i2: int) -> complex: ...
    def cdG(self, i1: int, i2: int) -> complex: ...
    def cdW(self, i1: int, i2: int) -> complex: ...
    def cdB(self, i1: int, i2: int) -> complex: ...
    def cHl1(self, i1: int, i2: int) -> complex: ...
    def cHl3(self, i1: int, i2: int) -> complex: ...
    def cHe(self, i1: int, i2: int) -> complex: ...
    def cHq1(self, i1: int, i2: int) -> complex: ...
    def cHq3(self, i1: int, i2: int) -> complex: ...
    def cHu(self, i1: int, i2: int) -> complex: ...
    def cHd(self, i1: int, i2: int) -> complex: ...
    def cHud(self, i1: int, i2: int) -> complex: ...
    def cll(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqq1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqq3(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def clq1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def clq3(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cee(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cuu(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cdd(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def ceu(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def ced(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cud1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cud8(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cle(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def clu(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cld(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqe(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqu1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqu8(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqd1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqd8(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cledq(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cquqd1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cquqd8(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def clequ1(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def clequ3(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cduq(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqqu(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cqqq(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
    def cduu(self, i1: int, i2: int, i3: int, i4: int) -> complex: ...
