#include "pch.h"
#include "OperatorImport.h"
#include "MSSM.h"

MSSM::MSSM(std::unordered_map<std::string, double> params) {
    if (params.find("cgamma") != params.end()) this->cgamma = params["cgamma"];
    if (params.find("g1") != params.end()) this->g1 = params["g1"];
    if (params.find("g2") != params.end()) this->g2 = params["g2"];
    if (params.find("g3") != params.end()) this->g3 = params["g3"];
    if (params.find("m1") != params.end()) this->m1 = params["m1"];
    if (params.find("m2") != params.end()) this->m2 = params["m2"];
    if (params.find("m3") != params.end()) this->m3 = params["m3"];
    if (params.find("mPhi") != params.end()) this->mPhi = params["mPhi"];
    if (params.find("muTilde") != params.end()) this->muTilde = params["muTilde"];
    if (params.find("mdt1") != params.end()) this->mdt[0] = params["mdt1"];
    if (params.find("mdt2") != params.end()) this->mdt[1] = params["mdt2"];
    if (params.find("mdt3") != params.end()) this->mdt[2] = params["mdt3"];
    if (params.find("met1") != params.end()) this->met[0] = params["met1"];
    if (params.find("met2") != params.end()) this->met[1] = params["met2"];
    if (params.find("met3") != params.end()) this->met[2] = params["met3"];
    if (params.find("mlt1") != params.end()) this->mlt[0] = params["mlt1"];
    if (params.find("mlt2") != params.end()) this->mlt[1] = params["mlt2"];
    if (params.find("mlt3") != params.end()) this->mlt[2] = params["mlt3"];
    if (params.find("mqt1") != params.end()) this->mqt[0] = params["mqt1"];
    if (params.find("mqt2") != params.end()) this->mqt[1] = params["mqt2"];
    if (params.find("mqt3") != params.end()) this->mqt[2] = params["mqt3"];
    if (params.find("mut1") != params.end()) this->mut[0] = params["mut1"];
    if (params.find("mut2") != params.end()) this->mut[1] = params["mut2"];
    if (params.find("mut3") != params.end()) this->mut[2] = params["mut3"];
    if (params.find("ad11") != params.end()) this->ad[0][0] = params["ad11"];
    if (params.find("ad12") != params.end()) this->ad[0][1] = params["ad12"];
    if (params.find("ad13") != params.end()) this->ad[0][2] = params["ad13"];
    if (params.find("ad21") != params.end()) this->ad[1][0] = params["ad21"];
    if (params.find("ad22") != params.end()) this->ad[1][1] = params["ad22"];
    if (params.find("ad23") != params.end()) this->ad[1][2] = params["ad23"];
    if (params.find("ad31") != params.end()) this->ad[2][0] = params["ad31"];
    if (params.find("ad32") != params.end()) this->ad[2][1] = params["ad32"];
    if (params.find("ad33") != params.end()) this->ad[2][2] = params["ad33"];
    if (params.find("ae11") != params.end()) this->ae[0][0] = params["ae11"];
    if (params.find("ae12") != params.end()) this->ae[0][1] = params["ae12"];
    if (params.find("ae13") != params.end()) this->ae[0][2] = params["ae13"];
    if (params.find("ae21") != params.end()) this->ae[1][0] = params["ae21"];
    if (params.find("ae22") != params.end()) this->ae[1][1] = params["ae22"];
    if (params.find("ae23") != params.end()) this->ae[1][2] = params["ae23"];
    if (params.find("ae31") != params.end()) this->ae[2][0] = params["ae31"];
    if (params.find("ae32") != params.end()) this->ae[2][1] = params["ae32"];
    if (params.find("ae33") != params.end()) this->ae[2][2] = params["ae33"];
    if (params.find("au11") != params.end()) this->au[0][0] = params["au11"];
    if (params.find("au12") != params.end()) this->au[0][1] = params["au12"];
    if (params.find("au13") != params.end()) this->au[0][2] = params["au13"];
    if (params.find("au21") != params.end()) this->au[1][0] = params["au21"];
    if (params.find("au22") != params.end()) this->au[1][1] = params["au22"];
    if (params.find("au23") != params.end()) this->au[1][2] = params["au23"];
    if (params.find("au31") != params.end()) this->au[2][0] = params["au31"];
    if (params.find("au32") != params.end()) this->au[2][1] = params["au32"];
    if (params.find("au33") != params.end()) this->au[2][2] = params["au33"];
    if (params.find("yd11") != params.end()) this->yd[0][0] = params["yd11"];
    if (params.find("yd12") != params.end()) this->yd[0][1] = params["yd12"];
    if (params.find("yd13") != params.end()) this->yd[0][2] = params["yd13"];
    if (params.find("yd21") != params.end()) this->yd[1][0] = params["yd21"];
    if (params.find("yd22") != params.end()) this->yd[1][1] = params["yd22"];
    if (params.find("yd23") != params.end()) this->yd[1][2] = params["yd23"];
    if (params.find("yd31") != params.end()) this->yd[2][0] = params["yd31"];
    if (params.find("yd32") != params.end()) this->yd[2][1] = params["yd32"];
    if (params.find("yd33") != params.end()) this->yd[2][2] = params["yd33"];
    if (params.find("ye11") != params.end()) this->ye[0][0] = params["ye11"];
    if (params.find("ye12") != params.end()) this->ye[0][1] = params["ye12"];
    if (params.find("ye13") != params.end()) this->ye[0][2] = params["ye13"];
    if (params.find("ye21") != params.end()) this->ye[1][0] = params["ye21"];
    if (params.find("ye22") != params.end()) this->ye[1][1] = params["ye22"];
    if (params.find("ye23") != params.end()) this->ye[1][2] = params["ye23"];
    if (params.find("ye31") != params.end()) this->ye[2][0] = params["ye31"];
    if (params.find("ye32") != params.end()) this->ye[2][1] = params["ye32"];
    if (params.find("ye33") != params.end()) this->ye[2][2] = params["ye33"];
    if (params.find("yu11") != params.end()) this->yu[0][0] = params["yu11"];
    if (params.find("yu12") != params.end()) this->yu[0][1] = params["yu12"];
    if (params.find("yu13") != params.end()) this->yu[0][2] = params["yu13"];
    if (params.find("yu21") != params.end()) this->yu[1][0] = params["yu21"];
    if (params.find("yu22") != params.end()) this->yu[1][1] = params["yu22"];
    if (params.find("yu23") != params.end()) this->yu[1][2] = params["yu23"];
    if (params.find("yu31") != params.end()) this->yu[2][0] = params["yu31"];
    if (params.find("yu32") != params.end()) this->yu[2][1] = params["yu32"];
    if (params.find("yu33") != params.end()) this->yu[2][2] = params["yu33"];
}

void MSSM::updateParams(std::unordered_map<std::string, double> params) {
    if (params.find("cgamma") != params.end()) this->cgamma = params["cgamma"];
    if (params.find("g1") != params.end()) this->g1 = params["g1"];
    if (params.find("g2") != params.end()) this->g2 = params["g2"];
    if (params.find("g3") != params.end()) this->g3 = params["g3"];
    if (params.find("m1") != params.end()) this->m1 = params["m1"];
    if (params.find("m2") != params.end()) this->m2 = params["m2"];
    if (params.find("m3") != params.end()) this->m3 = params["m3"];
    if (params.find("mPhi") != params.end()) this->mPhi = params["mPhi"];
    if (params.find("muTilde") != params.end()) this->muTilde = params["muTilde"];
    if (params.find("mdt1") != params.end()) this->mdt[0] = params["mdt1"];
    if (params.find("mdt2") != params.end()) this->mdt[1] = params["mdt2"];
    if (params.find("mdt3") != params.end()) this->mdt[2] = params["mdt3"];
    if (params.find("met1") != params.end()) this->met[0] = params["met1"];
    if (params.find("met2") != params.end()) this->met[1] = params["met2"];
    if (params.find("met3") != params.end()) this->met[2] = params["met3"];
    if (params.find("mlt1") != params.end()) this->mlt[0] = params["mlt1"];
    if (params.find("mlt2") != params.end()) this->mlt[1] = params["mlt2"];
    if (params.find("mlt3") != params.end()) this->mlt[2] = params["mlt3"];
    if (params.find("mqt1") != params.end()) this->mqt[0] = params["mqt1"];
    if (params.find("mqt2") != params.end()) this->mqt[1] = params["mqt2"];
    if (params.find("mqt3") != params.end()) this->mqt[2] = params["mqt3"];
    if (params.find("mut1") != params.end()) this->mut[0] = params["mut1"];
    if (params.find("mut2") != params.end()) this->mut[1] = params["mut2"];
    if (params.find("mut3") != params.end()) this->mut[2] = params["mut3"];
    if (params.find("ad11") != params.end()) this->ad[0][0] = params["ad11"];
    if (params.find("ad12") != params.end()) this->ad[0][1] = params["ad12"];
    if (params.find("ad13") != params.end()) this->ad[0][2] = params["ad13"];
    if (params.find("ad21") != params.end()) this->ad[1][0] = params["ad21"];
    if (params.find("ad22") != params.end()) this->ad[1][1] = params["ad22"];
    if (params.find("ad23") != params.end()) this->ad[1][2] = params["ad23"];
    if (params.find("ad31") != params.end()) this->ad[2][0] = params["ad31"];
    if (params.find("ad32") != params.end()) this->ad[2][1] = params["ad32"];
    if (params.find("ad33") != params.end()) this->ad[2][2] = params["ad33"];
    if (params.find("ae11") != params.end()) this->ae[0][0] = params["ae11"];
    if (params.find("ae12") != params.end()) this->ae[0][1] = params["ae12"];
    if (params.find("ae13") != params.end()) this->ae[0][2] = params["ae13"];
    if (params.find("ae21") != params.end()) this->ae[1][0] = params["ae21"];
    if (params.find("ae22") != params.end()) this->ae[1][1] = params["ae22"];
    if (params.find("ae23") != params.end()) this->ae[1][2] = params["ae23"];
    if (params.find("ae31") != params.end()) this->ae[2][0] = params["ae31"];
    if (params.find("ae32") != params.end()) this->ae[2][1] = params["ae32"];
    if (params.find("ae33") != params.end()) this->ae[2][2] = params["ae33"];
    if (params.find("au11") != params.end()) this->au[0][0] = params["au11"];
    if (params.find("au12") != params.end()) this->au[0][1] = params["au12"];
    if (params.find("au13") != params.end()) this->au[0][2] = params["au13"];
    if (params.find("au21") != params.end()) this->au[1][0] = params["au21"];
    if (params.find("au22") != params.end()) this->au[1][1] = params["au22"];
    if (params.find("au23") != params.end()) this->au[1][2] = params["au23"];
    if (params.find("au31") != params.end()) this->au[2][0] = params["au31"];
    if (params.find("au32") != params.end()) this->au[2][1] = params["au32"];
    if (params.find("au33") != params.end()) this->au[2][2] = params["au33"];
    if (params.find("yd11") != params.end()) this->yd[0][0] = params["yd11"];
    if (params.find("yd12") != params.end()) this->yd[0][1] = params["yd12"];
    if (params.find("yd13") != params.end()) this->yd[0][2] = params["yd13"];
    if (params.find("yd21") != params.end()) this->yd[1][0] = params["yd21"];
    if (params.find("yd22") != params.end()) this->yd[1][1] = params["yd22"];
    if (params.find("yd23") != params.end()) this->yd[1][2] = params["yd23"];
    if (params.find("yd31") != params.end()) this->yd[2][0] = params["yd31"];
    if (params.find("yd32") != params.end()) this->yd[2][1] = params["yd32"];
    if (params.find("yd33") != params.end()) this->yd[2][2] = params["yd33"];
    if (params.find("ye11") != params.end()) this->ye[0][0] = params["ye11"];
    if (params.find("ye12") != params.end()) this->ye[0][1] = params["ye12"];
    if (params.find("ye13") != params.end()) this->ye[0][2] = params["ye13"];
    if (params.find("ye21") != params.end()) this->ye[1][0] = params["ye21"];
    if (params.find("ye22") != params.end()) this->ye[1][1] = params["ye22"];
    if (params.find("ye23") != params.end()) this->ye[1][2] = params["ye23"];
    if (params.find("ye31") != params.end()) this->ye[2][0] = params["ye31"];
    if (params.find("ye32") != params.end()) this->ye[2][1] = params["ye32"];
    if (params.find("ye33") != params.end()) this->ye[2][2] = params["ye33"];
    if (params.find("yu11") != params.end()) this->yu[0][0] = params["yu11"];
    if (params.find("yu12") != params.end()) this->yu[0][1] = params["yu12"];
    if (params.find("yu13") != params.end()) this->yu[0][2] = params["yu13"];
    if (params.find("yu21") != params.end()) this->yu[1][0] = params["yu21"];
    if (params.find("yu22") != params.end()) this->yu[1][1] = params["yu22"];
    if (params.find("yu23") != params.end()) this->yu[1][2] = params["yu23"];
    if (params.find("yu31") != params.end()) this->yu[2][0] = params["yu31"];
    if (params.find("yu32") != params.end()) this->yu[2][1] = params["yu32"];
    if (params.find("yu33") != params.end()) this->yu[2][2] = params["yu33"];
}

void MSSM::printParamNames(){
    std::cout << "\nScalar-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "cgamma" << "\n";
    std::cout << "g1" << "\n";
    std::cout << "g2" << "\n";
    std::cout << "g3" << "\n";
    std::cout << "m1" << "\n";
    std::cout << "m2" << "\n";
    std::cout << "m3" << "\n";
    std::cout << "mPhi" << "\n";
    std::cout << "muTilde" << "\n";

    std::cout << "\nVector-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "mdt" << "\n";
    std::cout << "met" << "\n";
    std::cout << "mlt" << "\n";
    std::cout << "mqt" << "\n";
    std::cout << "mut" << "\n";

    std::cout << "\nMatrix-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "ad" << "\n";
    std::cout << "ae" << "\n";
    std::cout << "au" << "\n";
    std::cout << "yd" << "\n";
    std::cout << "ye" << "\n";
    std::cout << "yu" << "\n";

}

void MSSM::printParams(){
    std::cout << "\nScalar-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "cgamma: " << cgamma << "\n";
    std::cout << "g1: " << g1 << "\n";
    std::cout << "g2: " << g2 << "\n";
    std::cout << "g3: " << g3 << "\n";
    std::cout << "m1: " << m1 << "\n";
    std::cout << "m2: " << m2 << "\n";
    std::cout << "m3: " << m3 << "\n";
    std::cout << "mPhi: " << mPhi << "\n";
    std::cout << "muTilde: " << muTilde << "\n";

    std::cout << "\nVector-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "mdt1: " << mdt[0] << "\n";
    std::cout << "mdt2: " << mdt[1] << "\n";
    std::cout << "mdt3: " << mdt[2] << "\n";
    std::cout << "met1: " << met[0] << "\n";
    std::cout << "met2: " << met[1] << "\n";
    std::cout << "met3: " << met[2] << "\n";
    std::cout << "mlt1: " << mlt[0] << "\n";
    std::cout << "mlt2: " << mlt[1] << "\n";
    std::cout << "mlt3: " << mlt[2] << "\n";
    std::cout << "mqt1: " << mqt[0] << "\n";
    std::cout << "mqt2: " << mqt[1] << "\n";
    std::cout << "mqt3: " << mqt[2] << "\n";
    std::cout << "mut1: " << mut[0] << "\n";
    std::cout << "mut2: " << mut[1] << "\n";
    std::cout << "mut3: " << mut[2] << "\n";

    std::cout << "\nMatrix-valued parameters" << "\n";
    std::cout << "-----------------" << "\n";
    std::cout << "ad11: " << ad[0][0] << "\n";
    std::cout << "ad12: " << ad[0][1] << "\n";
    std::cout << "ad13: " << ad[0][2] << "\n";
    std::cout << "ad21: " << ad[1][0] << "\n";
    std::cout << "ad22: " << ad[1][1] << "\n";
    std::cout << "ad23: " << ad[1][2] << "\n";
    std::cout << "ad31: " << ad[2][0] << "\n";
    std::cout << "ad32: " << ad[2][1] << "\n";
    std::cout << "ad33: " << ad[2][2] << "\n";
    std::cout << "ae11: " << ae[0][0] << "\n";
    std::cout << "ae12: " << ae[0][1] << "\n";
    std::cout << "ae13: " << ae[0][2] << "\n";
    std::cout << "ae21: " << ae[1][0] << "\n";
    std::cout << "ae22: " << ae[1][1] << "\n";
    std::cout << "ae23: " << ae[1][2] << "\n";
    std::cout << "ae31: " << ae[2][0] << "\n";
    std::cout << "ae32: " << ae[2][1] << "\n";
    std::cout << "ae33: " << ae[2][2] << "\n";
    std::cout << "au11: " << au[0][0] << "\n";
    std::cout << "au12: " << au[0][1] << "\n";
    std::cout << "au13: " << au[0][2] << "\n";
    std::cout << "au21: " << au[1][0] << "\n";
    std::cout << "au22: " << au[1][1] << "\n";
    std::cout << "au23: " << au[1][2] << "\n";
    std::cout << "au31: " << au[2][0] << "\n";
    std::cout << "au32: " << au[2][1] << "\n";
    std::cout << "au33: " << au[2][2] << "\n";
    std::cout << "yd11: " << yd[0][0] << "\n";
    std::cout << "yd12: " << yd[0][1] << "\n";
    std::cout << "yd13: " << yd[0][2] << "\n";
    std::cout << "yd21: " << yd[1][0] << "\n";
    std::cout << "yd22: " << yd[1][1] << "\n";
    std::cout << "yd23: " << yd[1][2] << "\n";
    std::cout << "yd31: " << yd[2][0] << "\n";
    std::cout << "yd32: " << yd[2][1] << "\n";
    std::cout << "yd33: " << yd[2][2] << "\n";
    std::cout << "ye11: " << ye[0][0] << "\n";
    std::cout << "ye12: " << ye[0][1] << "\n";
    std::cout << "ye13: " << ye[0][2] << "\n";
    std::cout << "ye21: " << ye[1][0] << "\n";
    std::cout << "ye22: " << ye[1][1] << "\n";
    std::cout << "ye23: " << ye[1][2] << "\n";
    std::cout << "ye31: " << ye[2][0] << "\n";
    std::cout << "ye32: " << ye[2][1] << "\n";
    std::cout << "ye33: " << ye[2][2] << "\n";
    std::cout << "yu11: " << yu[0][0] << "\n";
    std::cout << "yu12: " << yu[0][1] << "\n";
    std::cout << "yu13: " << yu[0][2] << "\n";
    std::cout << "yu21: " << yu[1][0] << "\n";
    std::cout << "yu22: " << yu[1][1] << "\n";
    std::cout << "yu23: " << yu[1][2] << "\n";
    std::cout << "yu31: " << yu[2][0] << "\n";
    std::cout << "yu32: " << yu[2][1] << "\n";
    std::cout << "yu33: " << yu[2][2] << "\n";

}
