#include <pybind11/pybind11.h>
#include <pybind11/cast.h>
#include <pybind11/detail/common.h>
#include <pybind11/stl.h>
#include <pybind11/complex.h>
#include <unordered_map>
#include <string>
#include <complex>
#include "modelName.h"

namespace py = pybind11;

PYBIND11_MODULE(match_to_py, m, py::mod_gil_not_used()) {
    py::class_<Model>(m, py_class)
        .def(py::init<std::unordered_map<std::string, std::complex<double> > >())
        .def("updateParams", &Model::updateParams, py::arg("param_dict"))
        .def("cllHH", &Model::cllHH, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cG", &Model::cG, py::arg("mubarsq"), py::arg("hbar"))
        .def("cW", &Model::cW, py::arg("mubarsq"), py::arg("hbar"))
        .def("cGt", &Model::cGt, py::arg("mubarsq"), py::arg("hbar"))
        .def("cWt", &Model::cWt, py::arg("mubarsq"), py::arg("hbar"))
        .def("cH", &Model::cH, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHBox", &Model::cHBox, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHD", &Model::cHD, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHG", &Model::cHG, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHW", &Model::cHW, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHB", &Model::cHB, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHWB", &Model::cHWB, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHGt", &Model::cHGt, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHWt", &Model::cHWt, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHBt", &Model::cHBt, py::arg("mubarsq"), py::arg("hbar"))
        .def("cHWtB", &Model::cHWtB, py::arg("mubarsq"), py::arg("hbar"))
        .def("ceH", &Model::ceH, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cuH", &Model::cuH, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cdH", &Model::cdH, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("ceW", &Model::ceW, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("ceB", &Model::ceB, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cuG", &Model::cuG, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cuW", &Model::cuW, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cuB", &Model::cuB, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cdG", &Model::cdG, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cdW", &Model::cdW, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cdB", &Model::cdB, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHl1", &Model::cHl1, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHl3", &Model::cHl3, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHe", &Model::cHe, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHq1", &Model::cHq1, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHq3", &Model::cHq3, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHu", &Model::cHu, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHd", &Model::cHd, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cHud", &Model::cHud, py::arg("i1"), py::arg("i2"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cll", &Model::cll, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqq1", &Model::cqq1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqq3", &Model::cqq3, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("clq1", &Model::clq1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("clq3", &Model::clq3, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cee", &Model::cee, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cuu", &Model::cuu, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cdd", &Model::cdd, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("ceu", &Model::ceu, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("ced", &Model::ced, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cud1", &Model::cud1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cud8", &Model::cud8, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cle", &Model::cle, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("clu", &Model::clu, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cld", &Model::cld, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqe", &Model::cqe, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqu1", &Model::cqu1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqu8", &Model::cqu8, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqd1", &Model::cqd1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqd8", &Model::cqd8, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cledq", &Model::cledq, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cquqd1", &Model::cquqd1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cquqd8", &Model::cquqd8, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("clequ1", &Model::clequ1, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("clequ3", &Model::clequ3, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cduq", &Model::cduq, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqqu", &Model::cqqu, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cqqq", &Model::cqqq, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"))
        .def("cduu", &Model::cduu, py::arg("i1"), py::arg("i2"), py::arg("i3"), py::arg("i4"), py::arg("mubarsq"), py::arg("hbar"));
}
